### PR TITLE
fixed. ubuntu 20.04 (ghc 8.8.3) alway timeout error

### PR DESCRIPTION
**Pull request by Lupino**

### CODE REVIEW

**Comment by dustin** [comment]
This looks a bit strange to me.  I've not seen any timeouts and it's not clear to me how that particular strictness would matter from within conduit.  Do you have any more context as to how you're running into this issue?

**Comment by Lupino** [comment]
https://github.com/Lupino/yuntan-device/blob/master/src/Device/MQTT.hs#L145

this is my used code. 

in then orgin net-mqtt,      it running fine on ubuntu 18.04 and macos,  when i compile (stack resolver 15.12) on ubuntu 20.04 and run on 20.04,  mqtt error is alway `Timeout` ref https://github.com/Lupino/yuntan-device/blob/master/src/Device/MQTT.hs#L154

I debug with print,    i work fine on ubuntu 20.04,  then i add `$!` it work fine

**Comment by dustin** [comment]
Is there any chance you can get a packet trace here as well?  I'm trying to reproduce this behavior on NiXOS and it's a bit of a struggle for me.  It's not obvious to me how anything could work if this strictness needed forced.  If I can understand how this is failing a bit, it would help me understand if there are other places I should be concerned.

I don't think forcing here would *hurt* (though I wonder if, for example, `BangPatterns` also solves this problem), but it seems rather unique given how difficult it is to trigger.

**Comment by dustin** [comment]
I do have a case where I see something that looks a little bit like this occurring in my bridge.  I'm not sure if it's related, but I've been having some failures today against test.mosquitto.org, so at least I have a case to bring this in and try it out.

**Pull request merged**
